### ISSUE TITLE
违规提示

### ISSUE THREAD

**Issue by kihua** [zhuxuedefeng/AiQiangGUO#15]
不能就我一个被发现了吧👀![Screenshot_20210227_093046_com.vmos.pro.jpg](https://user-images.githubusercontent.com/68726177/109371245-0745ff00-78df-11eb-875b-5a4f32fa5f49.jpg)

**Comment by nqianaaron** [comment]
我两个号都被发现了。就今天

**Comment by kihua** [comment]
> 我两个号都被发现了。就今天

好家伙，这学习强国是开始强检测了吗

**Comment by 85524365** [comment]
用过模拟器或者电脑端吧？

**Comment by kihua** [comment]
> 用过模拟器或者电脑端吧？

对，之前用过一次电脑端的，不过都好几天了，时间也挺长，当时是测试那个软件

**Comment by nqianaaron** [comment]
我是用的模拟器，安装的apk

**Comment by kihua** [comment]
> 我是用的模拟器，安装的apk

我在手机虚拟机里用的，是不是答题太快被检测到的吧

**Comment by KB64ba** [comment]
> > 我是用的模拟器，安装的apk
> 
> 我在手机虚拟机里用的，是不是答题太快被检测到的吧

手机模拟器跟雷电一样啊，

**Comment by kihua** [comment]
所以在真机没事是吧，用模拟器就会检测👀

**Comment by zhuxuedefeng** [comment]
猜测模拟器，或者经常号码切换，一号多机，一机多号。目前我这单机单号使用正常。

**Comment by kihua** [comment]
> 猜测模拟器，或者经常号码切换，一号多机，一机多号。目前我这单机单号使用正常。

是的，用了模拟器，已经晓得了，现在都是在电脑油猴脚本刷视频，文章，然后这个apk用来答题
