### ISSUE TITLE
能不能优化下上游答题速度

### ISSUE THREAD

**Issue by mamiaox** [zhuxuedefeng/AiQiangGUO#2]
rt能不能优化下上游答题速度

**Comment by zhuxuedefeng** [comment]
@mamiaox 请自行下载代码优化。
注意:严禁收费代挂机，严禁收费传播，允许再次修改，但严禁修改时加入恶意代码，严禁未经修改核心代码逻辑即进行加密。使用风险自担。只保证代码无恶意代码。
