### ISSUE TITLE
文章视频优化

### ISSUE THREAD

**Issue by iSun0613** [zhuxuedefeng/AiQiangGUO#20]
文章这块儿，经常刷不到积分，因为某一天文章过少，要手动换分类，视频也是。作者大大看看有没有办法优化~另外题库有更新吗？

**Comment by zhuxuedefeng** [comment]
文章是点击发布平台，视频是点击发布日期。可参照lazystudy-onekey把已点击标题写入数据库，但最好修改为再次点击前搜库。点击关键词是按早期版本定的，确实不符合现在条件。

**Comment by zhuxuedefeng** [comment]
文章是点击发布平台，视频是点击发布日期。可参照lazystudy-onekey把已点击标题写入数据库，但最好修改为再次点击前搜库。点击关键词是按早期版本定的，确实不符合现在条件。
