### ISSUE TITLE
答题卡顿问题及死循环问题

### ISSUE THREAD

**Issue by EdwardXiaoran** [zhuxuedefeng/AiQiangGUO#21]
我的设备是红米note8pro，挂机时有清掉无关后台，关省电模式，版本v2.22.0-20210306

在线4人2人对战时，有时候会出现突然卡住，无任何操作，ui也无显示任何新内容，要手动点击选项

在单人答题时，出现多次填空题机器无法识别提示中的答案，无法自动填空，并出蓝字显示“未找到右上角按钮，尝试根据坐标点击 ，请手动处理” 
当尝试手动操作时又自动打开了提示页，打断了人工操作，需要修复此问题，建议在ui加一个暂停/启动选项

还有在线4人2人对战的题库有点旧了，需要更新，我这4人2人对战的点击答案有肉眼可见的延迟，希望也能改进下？

**Comment by wesley1910** [comment]
我也是

**Comment by xu19710308** [comment]
当地频道要手动点击

**Comment by zhuxuedefeng** [comment]
1，六控件题，AiQG现有代码不能正常提取到题目。该问题已有开发者解决，未引入。
2，专项/每周 题目内容与提示内容不一致，可以通过截图找色解决。
3，题库没有可靠的活跃题库，目前推荐用挑战答题刷题;代码 挑战 每日有延时。
4，本地频道控件位置经常变动，autojs分析下控件布局修改即可。
