### ISSUE TITLE
关于反监测的一丢丢想法

### ISSUE THREAD

**Issue by ElementClock** [zhuxuedefeng/AiQiangGUO#25]
脚本里某些行为明显是人所做不到的。如果增加些微小扰动会更合理。
在我要答题环节。会出现小弹窗提示。在人的逻辑下，需要点击确定之后，弹窗不会遮挡视线后再去选择想要答题的环节。而通过脚本直接选择答题环节不符合逻辑。如果官方从后台检测弹窗点击数据，分析发现未点击弹窗而直接答题的人明显是异常的。

**Comment by Nymph-star** [comment]
我想知道作者还在更新吗

**Comment by ElementClock** [comment]
> 我想知道作者还在更新吗

就目前版本号来说，最新的为3月6号发布的。在小米最新开发内测版系统上运行，仅在双人对战环节会出现一次卡死，其余无问题，够用。

**Comment by LailuoA77** [comment]
不知道开发者，还在开发没有，在我的手机上会出现进入主界面上不会进入本地频道，然后就一直卡了。本来想自己开发的，可是xuixiqiangguo，autojs无法采集控件，没法再修改。

**Comment by ElementClock** [comment]
> 不知道开发者，还在开发没有，在我的手机上会出现进入主界面上不会进入本地频道，然后就一直卡了。本来想自己开发的，可是xuixiqiangguo，autojs无法采集控件，没法再修改。

可以基于坐标点击啊

**Comment by zhuxuedefeng** [comment]
说明一下，只要没删库就是没跑路。。github手机不好上传，蓝奏云盘可以随时上传。
AiQiangGuo的设计理念是 打开自动跑完全流程，而不是保证答题全对，也就是说，它是解放双手的工具，不是抢答工具。所以题库不全，六控件题未做都是正常的。
题题都对，次次第一，容易被打出头鸟。

**Comment by zhuxuedefeng** [comment]
基于坐标点击不具普适性。

**Comment by Nymph-star** [comment]
> 说明一下，只要没删库就是没跑路。。github手机不好上传，蓝奏云盘可以随时上传。
> AiQiangGuo的设计理念是 打开自动跑完全流程，而不是保证答题全对，也就是说，它是解放双手的工具，不是抢答工具。所以题库不全，六控件题未做都是正常的。
> 题题都对，次次第一，容易被打出头鸟。


> > 不知道开发者，还在开发没有，在我的手机上会出现进入主界面上不会进入本地频道，然后就一直卡了。本来想自己开发的，可是xuixiqiangguo，autojs无法采集控件，没法再修改。
> 
> 可以基于坐标点击啊

没毛病
