### ISSUE TITLE
大佬，你这答题的更新题库是不是弄错了

### ISSUE THREAD

**Issue by lnxcyq** [zhuxuedefeng/AiQiangGUO#3]
大佬，你这答题的更新题库是不是弄错了。每日答题的更新还没毛病，但是挑战和争上游的也用？代码对不上吧

**Comment by zhuxuedefeng** [comment]
你是说自动更新题库的逻辑?
每日答题的逻辑是: 题库没有，查提示，单选题，如果按提示能正确找到答案点击，则更新到题库(多选与填空不更新，有部分题会干扰到挑战和争上游，毕竟他俩只单选)
挑战答题的逻辑是:题库没有，随机点击，随机点击正确(按上面那个错误标志判断，非逻辑)，则更新到题库。
争上游和对战因为无法判断正误，未做更新功能(也不是不能，可以通过截图找色，监听震动传感器等方法实现)。

**Comment by zhuxuedefeng** [comment]
每日和挑战更新题库功能，只是在提取题干和选项答案部分存在区别，这部分在各自模块内。拿到内容之后操作数据库 写入内容并无不同，故由同一段函数模块实现。

**Comment by lnxcyq** [comment]
if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" +
            "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists() || text("再来一局").exists())//遇到❌号，则答错了,不再通过结束本局字样判断
        { console.log("更新本地题库答案...");
          checkAndUpdate(question, answer, ClickAnswer);
        }
        console.log("---------------------------");
        return;
    }
这是挑战的更新，你没看你的checkAndUpdate(question, answer, ClickAnswer);能更新吗？

**Comment by zhuxuedefeng** [comment]
执行正常，亲*⸜( •ᴗ• )⸝*
实际执行几次。ui界面可以设置挑战答题次数+题数，单独拉起挑战答题。也就是所谓刷挑战题库，前后把tiku.db和数据库临时更改文件一起导出到电脑用sqllite工具查看，能看到更改正常，与log能匹配……
