### ISSUE TITLE
更新题库

### ISSUE THREAD

**Issue by aricyoung** [zhuxuedefeng/AiQiangGUO#4]
老大，可否更新题库？代码里有更新题库，可是注释掉了

**Comment by 85524365** [comment]
大神，旧版本支持挑战答题支持自定义次数和题数，所以可以用来挂机刷题库。
老大，貌似12.25不支持自定义刷题库了，还是希望能开开刷题库功能，这样可以保证争上游的胜率。

**Comment by zhuxuedefeng** [comment]
@aricyoung 更新题库部分代码拿到的格式不符合代码要求，且在线题库经常挂掉不稳定。要求:题目去除空格;词形题 注音题 二十四史题紧跟第一选项。
@85524365刷挑战一直在，看下你手机字体是不是放大了。标准字体大小可显示(位置有点偏下，下次删减下上面的东西提高下位置)。

**Comment by zhuxuedefeng** [comment]
题目去除空格，除特殊题跟第一选项外，不跟选项。如果您会处理，可以自行改代码。可以参考lazystudy项目，它处理在线题库是去首字，跟第一选项，对应代码搜题也是去首字，跟第一选项。忘了它带不带空格了。

**Comment by 85524365** [comment]
> @aricyoung 更新题库部分代码拿到的格式不符合代码要求，且在线题库经常挂掉不稳定。要求:题目去除空格;词形题 注音题 二十四史题紧跟第一选项。
> @85524365刷挑战一直在，看下你手机字体是不是放大了。标准字体大小可显示(位置有点偏下，下次删减下上面的东西提高下位置)。

谢谢大佬，华为p9屏幕太小，显示不全。
换了一块屏幕大点的手机，显示完整了，感谢🙏

**Comment by aricyoung** [comment]
我也是在学习这个js，以前不是用js的，我看了lazy的代码，它那个直接获得的是json结构数据，你注释掉的题库网址是html，确实去掉注释并调用会卡住，我现在还弄不明白有些代码的结果，看看吧。

**Comment by zhuxuedefeng** [comment]
@85524365可以下滑啊，亲。再不行也可以注释掉上面部分。像每日答题的按钮，文章视频的说明。。
@aricyoung 我也是编程入门，学着修改。数据库处理和json也不熟悉。代码复杂了也得慢慢理清。

**Comment by aricyoung** [comment]
@zhuxuedefeng 我呀，就是因为看到你们写的这个自动工具，才想学学js，哪敢啊，先学着。
