### ISSUE TITLE
一些使用体验看看能否解决

### ISSUE THREAD

**Issue by hillfangyu** [zhuxuedefeng/AiQiangGUO#5]
大佬，提一点使用体验看看能不能实现？
文章、视频循环你没解决，是否可以根据我的--历史中搜集历史信息，排除重复阅读？这样就不用每次看12+12还可能重复好几轮。
能否做成在线更新版本以及数据库？
每周答题和专项也可用全部查看是否完成判定？

**Comment by zhuxuedefeng** [comment]
1，无重大bug，不再考虑功能性更新。
2，文章 视频可以通过点击时提取标题写入数据库，刷新后读取标题匹配数据库来实现，lazystudy-onekey的解决思路。
3，在线更新版本，无自建网站。
4，在线更新题库，可以使用lazystudy的在线更新，但需按代码规则确定入库格式。题干只去除空格;注音题/词形题/二十四史题 题干去除空格紧跟第一选项。
5，每周专项问题，见1。有移植自lazystudy的相关代码，未做入口。

工具不推荐长期多次使用，禁止商业应用。
