### ISSUE TITLE
你好，安卓版本ai -强国请作者加入ai-强国app软件点开后自动运行脚本这个功能。

### ISSUE THREAD

**Issue by Benjamin-an** [zhuxuedefeng/AiQiangGUO#6]
安卓版本ai -强国，使用电视盒子作为运行环境，智能开关作为每天开关机定时，开机后配合autostarter自启软件-启动ai，启动ai后自动开始执行脚本任务，待2小时后，智能开关断电，当天任务结束。请作者加入ai-强国app软件点开后自动运行脚本——这个功能。

**Comment by zhuxuedefeng** [comment]
建议选用lazystudy no ui系列，不通过ui，直接调用主程序代码即可。
