### ISSUE TITLE
弹出无障碍授权设置菜单，然后就无反应，返回界面后卡死

### ISSUE THREAD

**Issue by ggggggggggithub** [zhuxuedefeng/AiQiangGUO#8]
点击开始后自动弹出无障碍授权设置菜单，然后就无反应，返回界面后卡死，显示autojs无响应

**Comment by affaff1** [comment]
+1

**Comment by zhuxuedefeng** [comment]
权限提前开启，之前Ai强国 APK也强调过这一点，无障碍权限一定要提前开启。有的手机系统会后台关闭长时间未使用的无障碍权限，此时打开app时提前在系统设置中打开无障碍权限（关闭再重新开启一次）。@ggggggggggithub @affaff1
