### ISSUE TITLE
老大版本不更新了吗

### ISSUE THREAD

**Issue by szsyzx** [zhuxuedefeng/AiQiangGUO#9]
老大版本不更新了吗

**Comment by zhuxuedefeng** [comment]
本版本无使用问题

**Comment by 85524365** [comment]
> 本版本无使用问题

大神，不知咋滴，看文章和视频，总是提示反复学习第一个文章或视频，进入不了第二个。

谢谢大神

**Comment by aweder** [comment]
> 使用问题

可以自己调整，我调整了一下文章或视频的获取方式，你可以参考一下：
`for (let i = 0; i < vCount;) {
            let articles = id("general_card_title_id").find();
            console.log("找到文章：" + articles.length)
            for (let article of articles) {
                //查找是否存在播报，如果存在则为文章
                let report = article.parent().parent().findOne(text("播报"));
                if (!report) {
                    let title = article.text();
                    let flag = Utils.getLearnedArticle(title, date_string, user);
                    if (!flag) {
                        console.log("观看第【" + (i + 1) + "】个视频：" + title);
                        if (click(title)) {
                            let n = 0;
                            while (!textContains("欢迎发表你的观点").exists()) {//如果没有找到评论框则认为没有进入文章界面，一直等待
                                Utils.delay(1);
                                console.warn("正在等待加载视频界面...");
                                if (n > 3) {//等待超过3秒则认为进入了专题界面，退出
                                    console.warn("没找到评论框!该界面非文章界面!");
                                    zt_flag = true;
                                    break;
                                }
                                n++;
                            }

                            //不存在播放，则为非视频
                            if (!textContains("播放").exists) {
                                back();
                                continue;
                            }

                            //进入专题页标志
                            if (zt_flag) {
                                console.warn("进入了专题界面，即将退出!");
                                back();
                                Utils.delay(1);
                                zt_flag = false;
                                continue;
                            }

                            //将文章插入到数据库中
                            Utils.insertLearnedArticle(title, date_string, user);
                            video_timing_news(i, vTime + random(-5, 10));
                            vCount--;
                            i++;
                            back()
                            Utils.delay(1);
                            if (vCount == 0) {
                                break;
                            }
                        } else {
                            console.log("点击视频失败")
                        }
                    }
                }
            }
            console.log("滑动翻页")
            listview.scrollForward();
            Utils.delay(1.5);
        }`

**Comment by 85524365** [comment]
> > 使用问题
> 
> 可以自己调整，我调整了一下文章或视频的获取方式，你可以参考一下：
> `for (let i = 0; i < vCount;) {
> let articles = id("general_card_title_id").find();
> console.log("找到文章：" + articles.length)
> for (let article of articles) {
> //查找是否存在播报，如果存在则为文章
> let report = article.parent().parent().findOne(text("播报"));
> if (!report) {
> let title = article.text();
> let flag = Utils.getLearnedArticle(title, date_string, user);
> if (!flag) {
> console.log("观看第【" + (i + 1) + "】个视频：" + title);
> if (click(title)) {
> let n = 0;
> while (!textContains("欢迎发表你的观点").exists()) {//如果没有找到评论框则认为没有进入文章界面，一直等待
> Utils.delay(1);
> console.warn("正在等待加载视频界面...");
> if (n > 3) {//等待超过3秒则认为进入了专题界面，退出
> console.warn("没找到评论框!该界面非文章界面!");
> zt_flag = true;
> break;
> }
> n++;
> }
> 
> ```
>                         //不存在播放，则为非视频
>                         if (!textContains("播放").exists) {
>                             back();
>                             continue;
>                         }
> 
>                         //进入专题页标志
>                         if (zt_flag) {
>                             console.warn("进入了专题界面，即将退出!");
>                             back();
>                             Utils.delay(1);
>                             zt_flag = false;
>                             continue;
>                         }
> 
>                         //将文章插入到数据库中
>                         Utils.insertLearnedArticle(title, date_string, user);
>                         video_timing_news(i, vTime + random(-5, 10));
>                         vCount--;
>                         i++;
>                         back()
>                         Utils.delay(1);
>                         if (vCount == 0) {
>                             break;
>                         }
>                     } else {
>                         console.log("点击视频失败")
>                     }
>                 }
>             }
>         }
>         console.log("滑动翻页")
>         listview.scrollForward();
>         Utils.delay(1.5);
>     }`
> ```

大神就是大神，膜拜
